variable "region" {}
variable "Task_name" {}
variable "main_cidr" {}
variable "public1_cidr" {}
variable "public2_cidr" {}
variable "private1_cidr" {}
variable "private2_cidr" {}
variable "Environment" {}
variable "instance_type" {}
variable "key_name" {}
variable "domain" {}